//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projedosyası
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emanet_Kitap_Alanlar
    {
        public int ID { get; set; }
        public string EmanetKitap_Barkod { get; set; }
        public string EmanetKitap_Adi { get; set; }
        public string EmanetKitap_Yazar { get; set; }
        public string EmanetKitap_Turu { get; set; }
        public Nullable<int> EmanetKitap_Basimyili { get; set; }
        public Nullable<int> EmanetKitap_ID { get; set; }
        public string EmanetAlan_Adi { get; set; }
        public string EmanetAlan_Email { get; set; }
        public Nullable<decimal> EmanetAlan_TCno { get; set; }
        public Nullable<decimal> EmanetAlan_Tel { get; set; }
        public Nullable<System.DateTime> EmanetAldiği_Tarih { get; set; }
        public Nullable<int> EmanetAlan_ID { get; set; }
        public string EmanetAlan_Soyad { get; set; }
    }
}
