namespace projedosyası
{
    partial class KayitSayfasi
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(KayitSayfasi));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuTextBox1 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.LGirisYap = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.KaUye_SoyaditxtBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.KaUye_TeltxtBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.KaUye_TctxtBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuButtonCancel = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.UyeE_mailtxtBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.KaUye_AditxtBox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.K_Sifretxtbox = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuImageButton1 = new Bunifu.UI.WinForms.BunifuImageButton();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuButtonCancel)).BeginInit();
            this.SuspendLayout();
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = false;
            this.bunifuPictureBox1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(5)))), ((int)(((byte)(22)))), ((int)(((byte)(26)))));
            this.bunifuPictureBox1.BorderRadius = 0;
            this.bunifuPictureBox1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuPictureBox1.Image = global::projedosyası.Properties.Resources.eye_fill2;
            this.bunifuPictureBox1.IsCircle = false;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(211, 282);
            this.bunifuPictureBox1.Margin = new System.Windows.Forms.Padding(0);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(26, 26);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.CenterImage;
            this.bunifuPictureBox1.TabIndex = 42;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Custom;
            this.bunifuPictureBox1.Click += new System.EventHandler(this.bunifuPictureBox1_Click);
            // 
            // bunifuTextBox1
            // 
            this.bunifuTextBox1.AcceptsReturn = false;
            this.bunifuTextBox1.AcceptsTab = false;
            this.bunifuTextBox1.AnimationSpeed = 200;
            this.bunifuTextBox1.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bunifuTextBox1.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bunifuTextBox1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuTextBox1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuTextBox1.BackgroundImage")));
            this.bunifuTextBox1.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bunifuTextBox1.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuTextBox1.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuTextBox1.BorderColorIdle = System.Drawing.Color.Silver;
            this.bunifuTextBox1.BorderRadius = 3;
            this.bunifuTextBox1.BorderThickness = 1;
            this.bunifuTextBox1.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bunifuTextBox1.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bunifuTextBox1.DefaultText = "";
            this.bunifuTextBox1.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(243)))), ((int)(((byte)(204)))));
            this.bunifuTextBox1.HideSelection = true;
            this.bunifuTextBox1.IconLeft = null;
            this.bunifuTextBox1.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.IconPadding = 10;
            this.bunifuTextBox1.IconRight = null;
            this.bunifuTextBox1.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bunifuTextBox1.Lines = new string[0];
            this.bunifuTextBox1.Location = new System.Drawing.Point(33, 313);
            this.bunifuTextBox1.MaxLength = 32767;
            this.bunifuTextBox1.MinimumSize = new System.Drawing.Size(1, 1);
            this.bunifuTextBox1.Modified = false;
            this.bunifuTextBox1.Multiline = false;
            this.bunifuTextBox1.Name = "bunifuTextBox1";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bunifuTextBox1.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(243)))), ((int)(((byte)(204)))));
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bunifuTextBox1.OnIdleState = stateProperties4;
            this.bunifuTextBox1.Padding = new System.Windows.Forms.Padding(3);
            this.bunifuTextBox1.PasswordChar = '\0';
            this.bunifuTextBox1.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.bunifuTextBox1.PlaceholderText = "Girdiğiniz Şifreyi Doğrulayın";
            this.bunifuTextBox1.ReadOnly = false;
            this.bunifuTextBox1.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bunifuTextBox1.SelectedText = "";
            this.bunifuTextBox1.SelectionLength = 0;
            this.bunifuTextBox1.SelectionStart = 0;
            this.bunifuTextBox1.ShortcutsEnabled = true;
            this.bunifuTextBox1.Size = new System.Drawing.Size(204, 26);
            this.bunifuTextBox1.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.bunifuTextBox1.TabIndex = 7;
            this.bunifuTextBox1.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuTextBox1.TextMarginBottom = 0;
            this.bunifuTextBox1.TextMarginLeft = 3;
            this.bunifuTextBox1.TextMarginTop = 0;
            this.bunifuTextBox1.TextPlaceholder = "Girdiğiniz Şifreyi Doğrulayın";
            this.bunifuTextBox1.UseSystemPasswordChar = false;
            this.bunifuTextBox1.WordWrap = true;
            this.bunifuTextBox1.TextChanged += new System.EventHandler(this.bunifuTextBox1_TextChanged);
            // 
            // LGirisYap
            // 
            this.LGirisYap.AllowAnimations = true;
            this.LGirisYap.AllowMouseEffects = true;
            this.LGirisYap.AllowToggling = false;
            this.LGirisYap.AnimationSpeed = 200;
            this.LGirisYap.AutoGenerateColors = false;
            this.LGirisYap.AutoRoundBorders = false;
            this.LGirisYap.AutoSizeLeftIcon = true;
            this.LGirisYap.AutoSizeRightIcon = true;
            this.LGirisYap.BackColor = System.Drawing.Color.Transparent;
            this.LGirisYap.BackColor1 = System.Drawing.Color.PaleTurquoise;
            this.LGirisYap.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("LGirisYap.BackgroundImage")));
            this.LGirisYap.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LGirisYap.ButtonText = "KAYDI TAMAMLA";
            this.LGirisYap.ButtonTextMarginLeft = 0;
            this.LGirisYap.ColorContrastOnClick = 45;
            this.LGirisYap.ColorContrastOnHover = 45;
            this.LGirisYap.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.LGirisYap.CustomizableEdges = borderEdges1;
            this.LGirisYap.DialogResult = System.Windows.Forms.DialogResult.None;
            this.LGirisYap.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.LGirisYap.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.LGirisYap.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.LGirisYap.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.LGirisYap.Font = new System.Drawing.Font("Segoe UI", 9.25F);
            this.LGirisYap.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(5)))), ((int)(((byte)(22)))), ((int)(((byte)(26)))));
            this.LGirisYap.IconLeftAlign = System.Drawing.ContentAlignment.TopRight;
            this.LGirisYap.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.LGirisYap.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.LGirisYap.IconMarginLeft = 11;
            this.LGirisYap.IconPadding = 10;
            this.LGirisYap.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.LGirisYap.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.LGirisYap.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.LGirisYap.IconSize = 25;
            this.LGirisYap.IdleBorderColor = System.Drawing.Color.PaleTurquoise;
            this.LGirisYap.IdleBorderRadius = 5;
            this.LGirisYap.IdleBorderThickness = 1;
            this.LGirisYap.IdleFillColor = System.Drawing.Color.PaleTurquoise;
            this.LGirisYap.IdleIconLeftImage = null;
            this.LGirisYap.IdleIconRightImage = null;
            this.LGirisYap.IndicateFocus = false;
            this.LGirisYap.Location = new System.Drawing.Point(33, 344);
            this.LGirisYap.Margin = new System.Windows.Forms.Padding(2);
            this.LGirisYap.Name = "LGirisYap";
            this.LGirisYap.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.LGirisYap.OnDisabledState.BorderRadius = 5;
            this.LGirisYap.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LGirisYap.OnDisabledState.BorderThickness = 1;
            this.LGirisYap.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.LGirisYap.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.LGirisYap.OnDisabledState.IconLeftImage = null;
            this.LGirisYap.OnDisabledState.IconRightImage = null;
            this.LGirisYap.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.LGirisYap.onHoverState.BorderRadius = 5;
            this.LGirisYap.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LGirisYap.onHoverState.BorderThickness = 1;
            this.LGirisYap.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.LGirisYap.onHoverState.ForeColor = System.Drawing.Color.White;
            this.LGirisYap.onHoverState.IconLeftImage = null;
            this.LGirisYap.onHoverState.IconRightImage = null;
            this.LGirisYap.OnIdleState.BorderColor = System.Drawing.Color.PaleTurquoise;
            this.LGirisYap.OnIdleState.BorderRadius = 5;
            this.LGirisYap.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LGirisYap.OnIdleState.BorderThickness = 1;
            this.LGirisYap.OnIdleState.FillColor = System.Drawing.Color.PaleTurquoise;
            this.LGirisYap.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(5)))), ((int)(((byte)(22)))), ((int)(((byte)(26)))));
            this.LGirisYap.OnIdleState.IconLeftImage = null;
            this.LGirisYap.OnIdleState.IconRightImage = null;
            this.LGirisYap.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.LGirisYap.OnPressedState.BorderRadius = 5;
            this.LGirisYap.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.LGirisYap.OnPressedState.BorderThickness = 1;
            this.LGirisYap.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.LGirisYap.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.LGirisYap.OnPressedState.IconLeftImage = null;
            this.LGirisYap.OnPressedState.IconRightImage = null;
            this.LGirisYap.Size = new System.Drawing.Size(204, 25);
            this.LGirisYap.TabIndex = 8;
            this.LGirisYap.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.LGirisYap.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.LGirisYap.TextMarginLeft = 0;
            this.LGirisYap.TextPadding = new System.Windows.Forms.Padding(0);
            this.LGirisYap.UseDefaultRadiusAndThickness = true;
            this.LGirisYap.Click += new System.EventHandler(this.LGirisYap_Click);
            // 
            // KaUye_SoyaditxtBox
            // 
            this.KaUye_SoyaditxtBox.AcceptsReturn = false;
            this.KaUye_SoyaditxtBox.AcceptsTab = false;
            this.KaUye_SoyaditxtBox.AnimationSpeed = 200;
            this.KaUye_SoyaditxtBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.KaUye_SoyaditxtBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.KaUye_SoyaditxtBox.BackColor = System.Drawing.Color.Transparent;
            this.KaUye_SoyaditxtBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("KaUye_SoyaditxtBox.BackgroundImage")));
            this.KaUye_SoyaditxtBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.KaUye_SoyaditxtBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.KaUye_SoyaditxtBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.KaUye_SoyaditxtBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.KaUye_SoyaditxtBox.BorderRadius = 3;
            this.KaUye_SoyaditxtBox.BorderThickness = 1;
            this.KaUye_SoyaditxtBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.KaUye_SoyaditxtBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.KaUye_SoyaditxtBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.KaUye_SoyaditxtBox.DefaultText = "";
            this.KaUye_SoyaditxtBox.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(243)))), ((int)(((byte)(204)))));
            this.KaUye_SoyaditxtBox.HideSelection = true;
            this.KaUye_SoyaditxtBox.IconLeft = null;
            this.KaUye_SoyaditxtBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.KaUye_SoyaditxtBox.IconPadding = 10;
            this.KaUye_SoyaditxtBox.IconRight = null;
            this.KaUye_SoyaditxtBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.KaUye_SoyaditxtBox.Lines = new string[0];
            this.KaUye_SoyaditxtBox.Location = new System.Drawing.Point(33, 186);
            this.KaUye_SoyaditxtBox.MaxLength = 32767;
            this.KaUye_SoyaditxtBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.KaUye_SoyaditxtBox.Modified = false;
            this.KaUye_SoyaditxtBox.Multiline = false;
            this.KaUye_SoyaditxtBox.Name = "KaUye_SoyaditxtBox";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.KaUye_SoyaditxtBox.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.KaUye_SoyaditxtBox.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.KaUye_SoyaditxtBox.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(243)))), ((int)(((byte)(204)))));
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.KaUye_SoyaditxtBox.OnIdleState = stateProperties8;
            this.KaUye_SoyaditxtBox.Padding = new System.Windows.Forms.Padding(3);
            this.KaUye_SoyaditxtBox.PasswordChar = '\0';
            this.KaUye_SoyaditxtBox.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.KaUye_SoyaditxtBox.PlaceholderText = "Soyad";
            this.KaUye_SoyaditxtBox.ReadOnly = false;
            this.KaUye_SoyaditxtBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.KaUye_SoyaditxtBox.SelectedText = "";
            this.KaUye_SoyaditxtBox.SelectionLength = 0;
            this.KaUye_SoyaditxtBox.SelectionStart = 0;
            this.KaUye_SoyaditxtBox.ShortcutsEnabled = true;
            this.KaUye_SoyaditxtBox.Size = new System.Drawing.Size(204, 26);
            this.KaUye_SoyaditxtBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.KaUye_SoyaditxtBox.TabIndex = 3;
            this.KaUye_SoyaditxtBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.KaUye_SoyaditxtBox.TextMarginBottom = 0;
            this.KaUye_SoyaditxtBox.TextMarginLeft = 3;
            this.KaUye_SoyaditxtBox.TextMarginTop = 0;
            this.KaUye_SoyaditxtBox.TextPlaceholder = "Soyad";
            this.KaUye_SoyaditxtBox.UseSystemPasswordChar = false;
            this.KaUye_SoyaditxtBox.WordWrap = true;
            // 
            // KaUye_TeltxtBox
            // 
            this.KaUye_TeltxtBox.AcceptsReturn = false;
            this.KaUye_TeltxtBox.AcceptsTab = false;
            this.KaUye_TeltxtBox.AnimationSpeed = 200;
            this.KaUye_TeltxtBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.KaUye_TeltxtBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.KaUye_TeltxtBox.BackColor = System.Drawing.Color.Transparent;
            this.KaUye_TeltxtBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("KaUye_TeltxtBox.BackgroundImage")));
            this.KaUye_TeltxtBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.KaUye_TeltxtBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.KaUye_TeltxtBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.KaUye_TeltxtBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.KaUye_TeltxtBox.BorderRadius = 3;
            this.KaUye_TeltxtBox.BorderThickness = 1;
            this.KaUye_TeltxtBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.KaUye_TeltxtBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.KaUye_TeltxtBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.KaUye_TeltxtBox.DefaultText = "";
            this.KaUye_TeltxtBox.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(243)))), ((int)(((byte)(204)))));
            this.KaUye_TeltxtBox.HideSelection = true;
            this.KaUye_TeltxtBox.IconLeft = null;
            this.KaUye_TeltxtBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.KaUye_TeltxtBox.IconPadding = 10;
            this.KaUye_TeltxtBox.IconRight = null;
            this.KaUye_TeltxtBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.KaUye_TeltxtBox.Lines = new string[0];
            this.KaUye_TeltxtBox.Location = new System.Drawing.Point(33, 250);
            this.KaUye_TeltxtBox.MaxLength = 32767;
            this.KaUye_TeltxtBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.KaUye_TeltxtBox.Modified = false;
            this.KaUye_TeltxtBox.Multiline = false;
            this.KaUye_TeltxtBox.Name = "KaUye_TeltxtBox";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.KaUye_TeltxtBox.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.KaUye_TeltxtBox.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.KaUye_TeltxtBox.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(243)))), ((int)(((byte)(204)))));
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.KaUye_TeltxtBox.OnIdleState = stateProperties12;
            this.KaUye_TeltxtBox.Padding = new System.Windows.Forms.Padding(3);
            this.KaUye_TeltxtBox.PasswordChar = '\0';
            this.KaUye_TeltxtBox.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.KaUye_TeltxtBox.PlaceholderText = "Telefon Numaranızı Giriniz";
            this.KaUye_TeltxtBox.ReadOnly = false;
            this.KaUye_TeltxtBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.KaUye_TeltxtBox.SelectedText = "";
            this.KaUye_TeltxtBox.SelectionLength = 0;
            this.KaUye_TeltxtBox.SelectionStart = 0;
            this.KaUye_TeltxtBox.ShortcutsEnabled = true;
            this.KaUye_TeltxtBox.Size = new System.Drawing.Size(204, 26);
            this.KaUye_TeltxtBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.KaUye_TeltxtBox.TabIndex = 5;
            this.KaUye_TeltxtBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.KaUye_TeltxtBox.TextMarginBottom = 0;
            this.KaUye_TeltxtBox.TextMarginLeft = 3;
            this.KaUye_TeltxtBox.TextMarginTop = 0;
            this.KaUye_TeltxtBox.TextPlaceholder = "Telefon Numaranızı Giriniz";
            this.KaUye_TeltxtBox.UseSystemPasswordChar = false;
            this.KaUye_TeltxtBox.WordWrap = true;
            // 
            // KaUye_TctxtBox
            // 
            this.KaUye_TctxtBox.AcceptsReturn = false;
            this.KaUye_TctxtBox.AcceptsTab = false;
            this.KaUye_TctxtBox.AnimationSpeed = 200;
            this.KaUye_TctxtBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.KaUye_TctxtBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.KaUye_TctxtBox.BackColor = System.Drawing.Color.Transparent;
            this.KaUye_TctxtBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("KaUye_TctxtBox.BackgroundImage")));
            this.KaUye_TctxtBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.KaUye_TctxtBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.KaUye_TctxtBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.KaUye_TctxtBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.KaUye_TctxtBox.BorderRadius = 3;
            this.KaUye_TctxtBox.BorderThickness = 1;
            this.KaUye_TctxtBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.KaUye_TctxtBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.KaUye_TctxtBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.KaUye_TctxtBox.DefaultText = "";
            this.KaUye_TctxtBox.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(243)))), ((int)(((byte)(204)))));
            this.KaUye_TctxtBox.HideSelection = true;
            this.KaUye_TctxtBox.IconLeft = null;
            this.KaUye_TctxtBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.KaUye_TctxtBox.IconPadding = 10;
            this.KaUye_TctxtBox.IconRight = null;
            this.KaUye_TctxtBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.KaUye_TctxtBox.Lines = new string[0];
            this.KaUye_TctxtBox.Location = new System.Drawing.Point(33, 218);
            this.KaUye_TctxtBox.MaxLength = 32767;
            this.KaUye_TctxtBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.KaUye_TctxtBox.Modified = false;
            this.KaUye_TctxtBox.Multiline = false;
            this.KaUye_TctxtBox.Name = "KaUye_TctxtBox";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.KaUye_TctxtBox.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.KaUye_TctxtBox.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.KaUye_TctxtBox.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(243)))), ((int)(((byte)(204)))));
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.KaUye_TctxtBox.OnIdleState = stateProperties16;
            this.KaUye_TctxtBox.Padding = new System.Windows.Forms.Padding(3);
            this.KaUye_TctxtBox.PasswordChar = '\0';
            this.KaUye_TctxtBox.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.KaUye_TctxtBox.PlaceholderText = "T.C. Kimlik Numaranızı Giriniz ";
            this.KaUye_TctxtBox.ReadOnly = false;
            this.KaUye_TctxtBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.KaUye_TctxtBox.SelectedText = "";
            this.KaUye_TctxtBox.SelectionLength = 0;
            this.KaUye_TctxtBox.SelectionStart = 0;
            this.KaUye_TctxtBox.ShortcutsEnabled = true;
            this.KaUye_TctxtBox.Size = new System.Drawing.Size(204, 26);
            this.KaUye_TctxtBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.KaUye_TctxtBox.TabIndex = 4;
            this.KaUye_TctxtBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.KaUye_TctxtBox.TextMarginBottom = 0;
            this.KaUye_TctxtBox.TextMarginLeft = 4;
            this.KaUye_TctxtBox.TextMarginTop = 0;
            this.KaUye_TctxtBox.TextPlaceholder = "T.C. Kimlik Numaranızı Giriniz ";
            this.KaUye_TctxtBox.UseSystemPasswordChar = false;
            this.KaUye_TctxtBox.WordWrap = true;
            // 
            // bunifuButtonCancel
            // 
            this.bunifuButtonCancel.AllowFocused = false;
            this.bunifuButtonCancel.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuButtonCancel.AutoSizeHeight = true;
            this.bunifuButtonCancel.BorderRadius = 14;
            this.bunifuButtonCancel.Image = global::projedosyası.Properties.Resources.x_circle__2_;
            this.bunifuButtonCancel.IsCircle = true;
            this.bunifuButtonCancel.Location = new System.Drawing.Point(233, 11);
            this.bunifuButtonCancel.Margin = new System.Windows.Forms.Padding(0);
            this.bunifuButtonCancel.Name = "bunifuButtonCancel";
            this.bunifuButtonCancel.Size = new System.Drawing.Size(28, 28);
            this.bunifuButtonCancel.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuButtonCancel.TabIndex = 10;
            this.bunifuButtonCancel.TabStop = false;
            this.bunifuButtonCancel.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            this.bunifuButtonCancel.Click += new System.EventHandler(this.bunifuPictureBox4_Click);
            // 
            // UyeE_mailtxtBox
            // 
            this.UyeE_mailtxtBox.AcceptsReturn = false;
            this.UyeE_mailtxtBox.AcceptsTab = false;
            this.UyeE_mailtxtBox.AnimationSpeed = 200;
            this.UyeE_mailtxtBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.UyeE_mailtxtBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.UyeE_mailtxtBox.BackColor = System.Drawing.Color.Transparent;
            this.UyeE_mailtxtBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("UyeE_mailtxtBox.BackgroundImage")));
            this.UyeE_mailtxtBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.UyeE_mailtxtBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.UyeE_mailtxtBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.UyeE_mailtxtBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.UyeE_mailtxtBox.BorderRadius = 3;
            this.UyeE_mailtxtBox.BorderThickness = 1;
            this.UyeE_mailtxtBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.UyeE_mailtxtBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.UyeE_mailtxtBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.UyeE_mailtxtBox.DefaultText = "";
            this.UyeE_mailtxtBox.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(243)))), ((int)(((byte)(204)))));
            this.UyeE_mailtxtBox.HideSelection = true;
            this.UyeE_mailtxtBox.IconLeft = null;
            this.UyeE_mailtxtBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.UyeE_mailtxtBox.IconPadding = 10;
            this.UyeE_mailtxtBox.IconRight = null;
            this.UyeE_mailtxtBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.UyeE_mailtxtBox.Lines = new string[0];
            this.UyeE_mailtxtBox.Location = new System.Drawing.Point(33, 122);
            this.UyeE_mailtxtBox.MaxLength = 32767;
            this.UyeE_mailtxtBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.UyeE_mailtxtBox.Modified = false;
            this.UyeE_mailtxtBox.Multiline = false;
            this.UyeE_mailtxtBox.Name = "UyeE_mailtxtBox";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.UyeE_mailtxtBox.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.UyeE_mailtxtBox.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.UyeE_mailtxtBox.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(243)))), ((int)(((byte)(204)))));
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.UyeE_mailtxtBox.OnIdleState = stateProperties20;
            this.UyeE_mailtxtBox.Padding = new System.Windows.Forms.Padding(3);
            this.UyeE_mailtxtBox.PasswordChar = '\0';
            this.UyeE_mailtxtBox.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.UyeE_mailtxtBox.PlaceholderText = "E-mail";
            this.UyeE_mailtxtBox.ReadOnly = false;
            this.UyeE_mailtxtBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.UyeE_mailtxtBox.SelectedText = "";
            this.UyeE_mailtxtBox.SelectionLength = 0;
            this.UyeE_mailtxtBox.SelectionStart = 0;
            this.UyeE_mailtxtBox.ShortcutsEnabled = true;
            this.UyeE_mailtxtBox.Size = new System.Drawing.Size(204, 26);
            this.UyeE_mailtxtBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.UyeE_mailtxtBox.TabIndex = 1;
            this.UyeE_mailtxtBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.UyeE_mailtxtBox.TextMarginBottom = 0;
            this.UyeE_mailtxtBox.TextMarginLeft = 3;
            this.UyeE_mailtxtBox.TextMarginTop = 0;
            this.UyeE_mailtxtBox.TextPlaceholder = "E-mail";
            this.UyeE_mailtxtBox.UseSystemPasswordChar = false;
            this.UyeE_mailtxtBox.WordWrap = true;
            // 
            // KaUye_AditxtBox
            // 
            this.KaUye_AditxtBox.AcceptsReturn = false;
            this.KaUye_AditxtBox.AcceptsTab = false;
            this.KaUye_AditxtBox.AnimationSpeed = 200;
            this.KaUye_AditxtBox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.KaUye_AditxtBox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.KaUye_AditxtBox.BackColor = System.Drawing.Color.Transparent;
            this.KaUye_AditxtBox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("KaUye_AditxtBox.BackgroundImage")));
            this.KaUye_AditxtBox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.KaUye_AditxtBox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.KaUye_AditxtBox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.KaUye_AditxtBox.BorderColorIdle = System.Drawing.Color.Silver;
            this.KaUye_AditxtBox.BorderRadius = 3;
            this.KaUye_AditxtBox.BorderThickness = 1;
            this.KaUye_AditxtBox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.KaUye_AditxtBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.KaUye_AditxtBox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.KaUye_AditxtBox.DefaultText = "";
            this.KaUye_AditxtBox.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(243)))), ((int)(((byte)(204)))));
            this.KaUye_AditxtBox.HideSelection = true;
            this.KaUye_AditxtBox.IconLeft = null;
            this.KaUye_AditxtBox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.KaUye_AditxtBox.IconPadding = 10;
            this.KaUye_AditxtBox.IconRight = null;
            this.KaUye_AditxtBox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.KaUye_AditxtBox.Lines = new string[0];
            this.KaUye_AditxtBox.Location = new System.Drawing.Point(33, 154);
            this.KaUye_AditxtBox.MaxLength = 32767;
            this.KaUye_AditxtBox.MinimumSize = new System.Drawing.Size(1, 1);
            this.KaUye_AditxtBox.Modified = false;
            this.KaUye_AditxtBox.Multiline = false;
            this.KaUye_AditxtBox.Name = "KaUye_AditxtBox";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.KaUye_AditxtBox.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.KaUye_AditxtBox.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.KaUye_AditxtBox.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(243)))), ((int)(((byte)(204)))));
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.KaUye_AditxtBox.OnIdleState = stateProperties24;
            this.KaUye_AditxtBox.Padding = new System.Windows.Forms.Padding(3);
            this.KaUye_AditxtBox.PasswordChar = '\0';
            this.KaUye_AditxtBox.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.KaUye_AditxtBox.PlaceholderText = "Ad";
            this.KaUye_AditxtBox.ReadOnly = false;
            this.KaUye_AditxtBox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.KaUye_AditxtBox.SelectedText = "";
            this.KaUye_AditxtBox.SelectionLength = 0;
            this.KaUye_AditxtBox.SelectionStart = 0;
            this.KaUye_AditxtBox.ShortcutsEnabled = true;
            this.KaUye_AditxtBox.Size = new System.Drawing.Size(204, 26);
            this.KaUye_AditxtBox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.KaUye_AditxtBox.TabIndex = 2;
            this.KaUye_AditxtBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.KaUye_AditxtBox.TextMarginBottom = 0;
            this.KaUye_AditxtBox.TextMarginLeft = 3;
            this.KaUye_AditxtBox.TextMarginTop = 0;
            this.KaUye_AditxtBox.TextPlaceholder = "Ad";
            this.KaUye_AditxtBox.UseSystemPasswordChar = false;
            this.KaUye_AditxtBox.WordWrap = true;
            // 
            // K_Sifretxtbox
            // 
            this.K_Sifretxtbox.AcceptsReturn = false;
            this.K_Sifretxtbox.AcceptsTab = false;
            this.K_Sifretxtbox.AnimationSpeed = 200;
            this.K_Sifretxtbox.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.K_Sifretxtbox.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.K_Sifretxtbox.BackColor = System.Drawing.Color.Transparent;
            this.K_Sifretxtbox.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("K_Sifretxtbox.BackgroundImage")));
            this.K_Sifretxtbox.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.K_Sifretxtbox.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.K_Sifretxtbox.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.K_Sifretxtbox.BorderColorIdle = System.Drawing.Color.Silver;
            this.K_Sifretxtbox.BorderRadius = 3;
            this.K_Sifretxtbox.BorderThickness = 1;
            this.K_Sifretxtbox.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.K_Sifretxtbox.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.K_Sifretxtbox.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.K_Sifretxtbox.DefaultText = "";
            this.K_Sifretxtbox.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(243)))), ((int)(((byte)(204)))));
            this.K_Sifretxtbox.HideSelection = true;
            this.K_Sifretxtbox.IconLeft = null;
            this.K_Sifretxtbox.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.K_Sifretxtbox.IconPadding = 10;
            this.K_Sifretxtbox.IconRight = null;
            this.K_Sifretxtbox.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.K_Sifretxtbox.Lines = new string[0];
            this.K_Sifretxtbox.Location = new System.Drawing.Point(33, 282);
            this.K_Sifretxtbox.MaxLength = 32767;
            this.K_Sifretxtbox.MinimumSize = new System.Drawing.Size(1, 1);
            this.K_Sifretxtbox.Modified = false;
            this.K_Sifretxtbox.Multiline = false;
            this.K_Sifretxtbox.Name = "K_Sifretxtbox";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.K_Sifretxtbox.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.K_Sifretxtbox.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.K_Sifretxtbox.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(226)))), ((int)(((byte)(243)))), ((int)(((byte)(204)))));
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.K_Sifretxtbox.OnIdleState = stateProperties28;
            this.K_Sifretxtbox.Padding = new System.Windows.Forms.Padding(3);
            this.K_Sifretxtbox.PasswordChar = '\0';
            this.K_Sifretxtbox.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.K_Sifretxtbox.PlaceholderText = "Şifre";
            this.K_Sifretxtbox.ReadOnly = false;
            this.K_Sifretxtbox.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.K_Sifretxtbox.SelectedText = "";
            this.K_Sifretxtbox.SelectionLength = 0;
            this.K_Sifretxtbox.SelectionStart = 0;
            this.K_Sifretxtbox.ShortcutsEnabled = true;
            this.K_Sifretxtbox.Size = new System.Drawing.Size(204, 26);
            this.K_Sifretxtbox.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.K_Sifretxtbox.TabIndex = 6;
            this.K_Sifretxtbox.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.K_Sifretxtbox.TextMarginBottom = 0;
            this.K_Sifretxtbox.TextMarginLeft = 3;
            this.K_Sifretxtbox.TextMarginTop = 0;
            this.K_Sifretxtbox.TextPlaceholder = "Şifre";
            this.K_Sifretxtbox.UseSystemPasswordChar = false;
            this.K_Sifretxtbox.WordWrap = true;
            this.K_Sifretxtbox.TextChanged += new System.EventHandler(this.K_Sifretxtbox_TextChanged);
            // 
            // bunifuImageButton1
            // 
            this.bunifuImageButton1.ActiveImage = null;
            this.bunifuImageButton1.AllowAnimations = true;
            this.bunifuImageButton1.AllowBuffering = false;
            this.bunifuImageButton1.AllowToggling = false;
            this.bunifuImageButton1.AllowZooming = true;
            this.bunifuImageButton1.AllowZoomingOnFocus = false;
            this.bunifuImageButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton1.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.ErrorImage")));
            this.bunifuImageButton1.FadeWhenInactive = false;
            this.bunifuImageButton1.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.Image")));
            this.bunifuImageButton1.ImageActive = null;
            this.bunifuImageButton1.ImageLocation = null;
            this.bunifuImageButton1.ImageMargin = 1;
            this.bunifuImageButton1.ImageSize = new System.Drawing.Size(99, 96);
            this.bunifuImageButton1.ImageZoomSize = new System.Drawing.Size(100, 97);
            this.bunifuImageButton1.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.InitialImage")));
            this.bunifuImageButton1.Location = new System.Drawing.Point(90, 11);
            this.bunifuImageButton1.Margin = new System.Windows.Forms.Padding(2);
            this.bunifuImageButton1.Name = "bunifuImageButton1";
            this.bunifuImageButton1.Rotation = 0;
            this.bunifuImageButton1.ShowActiveImage = true;
            this.bunifuImageButton1.ShowCursorChanges = true;
            this.bunifuImageButton1.ShowImageBorders = true;
            this.bunifuImageButton1.ShowSizeMarkers = false;
            this.bunifuImageButton1.Size = new System.Drawing.Size(100, 97);
            this.bunifuImageButton1.TabIndex = 90;
            this.bunifuImageButton1.ToolTipText = "Resme tıklayarak değiştirebirsiniz";
            this.bunifuImageButton1.WaitOnLoad = false;
            this.bunifuImageButton1.Zoom = 1;
            this.bunifuImageButton1.ZoomSpeed = 10;
            // 
            // KayitSayfasi
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(5)))), ((int)(((byte)(22)))), ((int)(((byte)(26)))));
            this.ClientSize = new System.Drawing.Size(270, 380);
            this.Controls.Add(this.bunifuPictureBox1);
            this.Controls.Add(this.bunifuTextBox1);
            this.Controls.Add(this.LGirisYap);
            this.Controls.Add(this.KaUye_SoyaditxtBox);
            this.Controls.Add(this.KaUye_TeltxtBox);
            this.Controls.Add(this.KaUye_TctxtBox);
            this.Controls.Add(this.bunifuButtonCancel);
            this.Controls.Add(this.UyeE_mailtxtBox);
            this.Controls.Add(this.KaUye_AditxtBox);
            this.Controls.Add(this.K_Sifretxtbox);
            this.Controls.Add(this.bunifuImageButton1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(2);
            this.Name = "KayitSayfasi";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "KayitSayfasi";
            this.Load += new System.EventHandler(this.KayitSayfasi_Load);
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuButtonCancel)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton1;
        private Bunifu.UI.WinForms.BunifuTextBox KaUye_AditxtBox;
        private Bunifu.UI.WinForms.BunifuTextBox K_Sifretxtbox;
        private Bunifu.UI.WinForms.BunifuTextBox UyeE_mailtxtBox;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuButtonCancel;
        private Bunifu.UI.WinForms.BunifuTextBox KaUye_TctxtBox;
        private Bunifu.UI.WinForms.BunifuTextBox KaUye_TeltxtBox;
        private Bunifu.UI.WinForms.BunifuTextBox KaUye_SoyaditxtBox;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton LGirisYap;
        private Bunifu.UI.WinForms.BunifuTextBox bunifuTextBox1;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
    }
}