//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projedosyası
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kitaplarimiz
    {
        public int Kitap_ID { get; set; }
        public string Kitap_Barkod { get; set; }
        public string Kitap_Adi { get; set; }
        public string Kitap_yazar { get; set; }
        public string Kitap_Turu { get; set; }
        public string Kitap_Konusu { get; set; }
        public string Kitap_Yayinevi { get; set; }
        public Nullable<double> Kitap_basimyili { get; set; }
        public Nullable<int> Kitap_Adet { get; set; }
    }
}
