//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projedosyası
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kutuphane_Uye_listesi
    {
        public int Uye_ID { get; set; }
        public string Uye_Adi { get; set; }
        public string Uye_Soyadi { get; set; }
        public Nullable<decimal> Uye_Tc { get; set; }
        public string Uye_Email { get; set; }
        public Nullable<decimal> Uye_telefon { get; set; }
        public string Uye_Sifre { get; set; }
        public Nullable<int> Uye_Borc { get; set; }
        public Nullable<int> Uye_ToplamOkunan { get; set; }
        public string Uye_Yetki { get; set; }
    }
}
