//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projedosyası
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Kutuphane_ProjesiEntities5 : DbContext
    {
        public Kutuphane_ProjesiEntities5()
            : base("name=Kutuphane_ProjesiEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Emanet_Kitap_Alanlar> Emanet_Kitap_Alanlar { get; set; }
        public virtual DbSet<Kitaplarimiz> Kitaplarimiz { get; set; }
        public virtual DbSet<Kutuphane_Uye_listesi> Kutuphane_Uye_listesi { get; set; }
        public virtual DbSet<Personel_Listesi> Personel_Listesi { get; set; }
    }
}
