//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace projedosyası
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel_Listesi
    {
        public int Personel_ID { get; set; }
        public string Personel_Adi { get; set; }
        public string Personel_Soyadi { get; set; }
        public Nullable<int> Personel_Tc { get; set; }
        public string Personel_Email { get; set; }
        public Nullable<decimal> Personel_Telefon { get; set; }
    }
}
