//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace projedosyası
{
    #region Bağlamlar
    
    /// <summary>
    /// Kullanılabilir Meta Veri Belgeleri yok.
    /// </summary>
    public partial class Kutuphane_ProjesiEntities3 : ObjectContext
    {
        #region Oluşturucular
    
        /// <summary>
        /// Yeni Kutuphane_ProjesiEntities3 nesnesini, uygulama yapılandırma dosyasının 'Kutuphane_ProjesiEntities3' bölümünde bulunan bağlantı dizesini kullanarak başlatır.
        /// </summary>
        public Kutuphane_ProjesiEntities3() : base("name=Kutuphane_ProjesiEntities3", "Kutuphane_ProjesiEntities3")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Yeni bir Kutuphane_ProjesiEntities3 nesnesi başlatın.
        /// </summary>
        public Kutuphane_ProjesiEntities3(string connectionString) : base(connectionString, "Kutuphane_ProjesiEntities3")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Yeni bir Kutuphane_ProjesiEntities3 nesnesi başlatın.
        /// </summary>
        public Kutuphane_ProjesiEntities3(EntityConnection connection) : base(connection, "Kutuphane_ProjesiEntities3")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Kısmi Metotlar
    
        partial void OnContextCreated();
    
        #endregion
    
    }

    #endregion

}
